# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: ðŸ“ Docs issue
description: Report incorrect or missing content in docs, or a website issue
labels:
  - status/triage
  - documentation

body:
  - type: checkboxes
    attributes:
      label: â“ Is this a docs issue?
      description: |
        Use this issue for reporting issues related to Docker documentation.
        For product issues, refer to the corresponding product repository.
      options:
        - label: My issue is about the documentation content or website
          required: true
  - type: dropdown
    attributes:
      label: ðŸ—„ï¸ Type of issue
      description: What type of problem are you reporting?
      multiple: false
      options:
        - Information is incorrect
        - I can't find what I'm looking for
        - There's a problem with the website
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: ðŸ“œ Description
      description: |
        Briefly describe the problem that you found.
    validations:
      required: true
  - type: input
    id:  location
    attributes:
      label: ðŸ”— Location
      description: Where did you find the problem?
      placeholder: "https://docs.docker.com/"
    validations:
      required: true
  - type: textarea
    attributes:
      label: ðŸ’­ Suggestion
      description: >
        Let us know if you have specific ideas on how we can fix the issue.
